### ISSUE TITLE
Unable to join vanilla 1.13.2 Server

### ISSUE THREAD

**Issue by michaelsakharov** [Technoguyfication/Minecraft-Unity3D#1]
I can Connect, it gets to Downloading world and spawns some Entities, but then "Disconnected: Connection closed"

**Comment by michaelsakharov** [comment]
Setting server property View Distance to 5 solved the issue

**Comment by Technoguyfication** [comment]
Chunk loading performance has greatly improved. Default view distance should work fine now.
