### ISSUE TITLE
not actually an issue just wanna say something

### ISSUE THREAD

**Issue by Tanza3D** [Technoguyfication/Minecraft-Unity3D#2]
this is looking amazing atm, (sorry for using issue to say this)

i'll definetly be attempting to build it sometime soon and give it a go, this is looking awesome so far.

**Comment by Technoguyfication** [comment]
Didn't see this issue because it was closed. Thanks dude! I've been working on the project some more the past week and it's improved a lot!

**Comment by developer-ken** [comment]
Amazing project! I am used to write CSharp. When I want to mod the client myself, I hate writing mods in Java. With your project, I can have a client to realize my ideas without Java!
