### ISSUE TITLE
Cant connect to 1.14.4 vanilla server (brand new)

### ISSUE THREAD

**Issue by Tanza3D** [Technoguyfication/Minecraft-Unity3D#4]
Booted up a new vanilla 1.14.4 server at localhost:25566, attempted to connect and the loading screen freezes on "Connection established. Logging in..."

![image](https://user-images.githubusercontent.com/33783503/63222968-71d49580-c1a6-11e9-8cb5-811df603b1ce.png)
![image](https://user-images.githubusercontent.com/33783503/63222974-8749bf80-c1a6-11e9-8a4d-36e28c31cf6e.png)

No idea why this is happening, server console says nothing

![image](https://user-images.githubusercontent.com/33783503/63222976-916bbe00-c1a6-11e9-87d5-a470c727db73.png)

**Comment by Tanza3D** [comment]
After joining on normal vanilla minecraft, works fine, joining again still broken

**Comment by djgaven588** [comment]
If your trying to join with the same account, you will have issues at this time (if running from the editor, you can open the GameManager object and change the username property) . I am not sure if the project currently supports 1.14.4, but for sure it should work with 1.13.?.

**Comment by Tanza3D** [comment]
@djgaven588 no one is on the server at the time of logging in, so its completely empty with no one on it, there shouldnt be any problems with usernames. i'll give 1.13 a go in a min

**Comment by michaelsakharov** [comment]
Try Setting the Servers render distance inside the Server Properties to 5 Worked for me.

**Comment by Technoguyfication** [comment]
1.14 is not supported yet, in part due to lack of thorough documentation and because I'm trying to get some of the bigger features done before updating the protocol. Use 1.13.2 for now.
